FROM node:14-alpine3.13 as build

ENV HOME=/home/app/webapp
WORKDIR $HOME

ARG PORT
ARG HOST
ARG NODE_ENV
ARG APP_KEY
ARG DRIVE_DISK
ARG DB_CONNECTION
ARG PG_HOST
ARG PG_PORT
ARG PG_USER
ARG PG_PASSWORD
ARG PG_DB_NAME
ARG DAILY_API_URL
ARG DAILY_API_TOKEN

ENV PORT=$PORT\
  HOST=$HOST\
  NODE_ENV=$NODE_ENV\
  APP_KEY=$APP_KEY\
  DRIVE_DISK=$DRIVE_DISK\
  DB_CONNECTION=$DB_CONNECTION\
  PG_HOST=$PG_HOST\
  PG_PORT=$PG_PORT\
  PG_USER=$PG_USER\
  PG_PASSWORD=$PG_PASSWORD\
  PG_DB_NAME=$PG_DB_NAME\
  DAILY_API_URL=$DAILY_API_URL\
  DAILY_API_TOKEN=$DAILY_API_TOKEN


COPY package.json ./
RUN yarn install

ADD . /home/app/webapp
# COPY . /home/app
RUN yarn run build
RUN cd build
RUN yarn install --production

EXPOSE 80
WORKDIR $HOME/build
CMD ["node", "server.js"]
